### PR TITLE
Added version support.

### PR DESCRIPTION
**Pull request by saurabhbatra96**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Hey - I tend to try to support multiple versions in extensions where I can - the alternative is aggressively dropping support for older versions - which I'm less keen on. 

So, I'd probably prefer to do some 'if magic' to support both 4.7 & pre-4.7 versions (with enough comments to allow it to be removed later) - if (property_exists....// Oh look I'm 4.6 or earlier we'll remove this if one day...) } else...

**Comment by saurabhbatra96** [comment]
So I did add the version support option, however I noticed a small issue. Under Import Data File, the following message occurs:
"Maximum Upload File Size: 0 MB"

I checked and where it shows 0 mb, it's supposed to output the variable $uploadSize which is defined in this file by "$uploadSize = round(($uploadFileSize / (1024 * 1024)), 2);". Not sure if its just a small bug or that the maxFileSize property has not been set.

**Comment by eileenmcnaughton** [comment]
Hmm - so how does the core 'import contacts' work with 4.7?

**Comment by saurabhbatra96** [comment]
Found and fixed the bug. Ignore the email. It seems as if all that was needed was to convert the string into a number. This is working now.

**Comment by eileenmcnaughton** [comment]
Cool - merging!

**Pull request merged**
